### ISSUE TITLE
[Enhancement] "replace": false

### ISSUE THREAD

**Issue by BeansBeefBroccoli** [MostafaSabry55/More-Plates#15]
Add a config option for the tags not to include '"replace": true'. Also, can you tell me what piece of code does that? Thanks. 🙂

**Comment by MostafaSabry55** [comment]
I am really sorry but I won't be doing that any time soon, the mod's main purpose is unifying all plates, gears and rods, so there's really no reason to do that currently... May I know why you exactly want that?

**Comment by BeansBeefBroccoli** [comment]
Some mods don't have a JSON recipe system yet, and their recipes only use their item. You can fix this with KubeJS by making their item be the only one with the proper tags, but it's just more work for the modpack maker. Thanks for responding :)

**Comment by MostafaSabry55** [comment]
No problem, but for now this really isn't something that can be done easily from my side, only hope is that they support tag recipes!
